before_script:
  - asdf install
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle -v
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

stages:
  - lint
  - test

ruby_lint:
  stage: lint
  script: bundle exec rake rubocop

ruby_test:
  stage: test
  script: bundle exec rake spec
  coverage: '/\(\d+\.\d+\%\) covered/'
  artifacts:
    paths:
      - junit.xml
      - coverage/
    reports:
      junit: junit.xml
